version: '3.8'

services:
  # PostgreSQL Database - Centralized Health Records
  postgres:
    image: postgres:15-alpine
    container_name: medfayda-centralized-db
    environment:
      POSTGRES_DB: medfayda_central
      POSTGRES_USER: medfayda_admin
      POSTGRES_PASSWORD: EthiopiaHealth2024!
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/setup-database.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./backend/seed-data.sql:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - "5432:5432"
    networks:
      - medfayda-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medfayda_admin -d medfayda_central"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      postgres
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100

  # Backend API - Centralized Health Records System
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: medfayda-central-api
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=medfayda_central
      - DB_USER=medfayda_admin
      - DB_PASSWORD=EthiopiaHealth2024!
      - JWT_SECRET=Ethiopia_MedFayda_JWT_Secret_2024_Centralized_System
      - JWT_EXPIRES_IN=24h
      - SESSION_SECRET=Ethiopia_MedFayda_Session_Secret_2024_Secure
      - PORT=5000
      - FRONTEND_URL=http://localhost:3000
      - FAYDA_API_URL=https://api.fayda.gov.et
      - ENCRYPTION_KEY=Ethiopia_Health_Encryption_Key_2024
      - AUDIT_LOG_LEVEL=detailed
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - medfayda-network
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Web App - Multi-Portal Interface
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: medfayda-portal
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - NEXT_PUBLIC_APP_NAME=MedFayda Centralized Health System
      - NEXT_PUBLIC_FAYDA_URL=https://fayda.gov.et
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - medfayda-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  medfayda-network:
    driver: bridge
